upstream ggr {
	server ggr_ggr_1:5555 weight=10  max_fails=3 fail_timeout=10s;
	#server ggr_ggr_2:5555 weight=10  max_fails=3 fail_timeout=10s;
	#server ggr_ggr_3:5555 weight=10  max_fails=3 fail_timeout=10s;
	#server ggr_ggr_4:5555 weight=10  max_fails=3 fail_timeout=10s;
	#server ggr_ggr_5:5555 weight=10  max_fails=3 fail_timeout=10s;
	#server host.docker.internal:4447 weight=10  max_fails=3 fail_timeout=10s;
	#server host.docker.internal:4445 weight=10  max_fails=3 fail_timeout=10s;
}
server {
	listen 4444;
	server_name  localhost;
	
	location / {
		proxy_pass http://ggr;
	}
    proxy_connect_timeout 1200;
    proxy_send_timeout 1200;
    proxy_read_timeout 1200;
}

#server {
#	listen       8080;
#	server_name  localhost;
#
#	location / {
#		root   /usr/share/nginx/html;
#		index  index.html index.htm;
#	}
#
#	error_page   500 502 503 504  /50x.html;
#	location = /50x.html {
#		root   html;
#	}
#}
